### ISSUE TITLE
TaskActor Fails to Start Up 

### ISSUE THREAD

**Issue by nicgrayson** [vivint-smarthome/ceph-on-mesos#10]
Here is the section of the log I'm seeing the actor crash repeatedly. Let me know if you would like more context.

```
18:27:20.134 [ceph-on-mesos-akka.actor.default-dispatcher-3] DEBUG com.vivint.ceph.FrameworkActor - received 4 offers from mesos. Forwarding to TaskActor
18:27:33.399 [ceph-on-mesos-akka.actor.default-dispatcher-5-SendThread(10.158.15.164:2181)] DEBUG org.apache.zookeeper.ClientCnxn - Got ping response for sessionid: 0x158e0a1510b299a after 10ms
18:27:34.999 [ceph-on-mesos-akka.actor.default-dispatcher-7] ERROR akka.actor.OneForOneStrategy - Timeout while initializing TaskActor
java.util.concurrent.TimeoutException: Timeout while initializing TaskActor
	at com.vivint.ceph.TaskActor$$anonfun$startInitialization$1.applyOrElse(TaskActor.scala:130)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:484)
	at com.vivint.ceph.TaskActor.aroundReceive(TaskActor.scala:36)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
18:27:35.012 [ceph-on-mesos-akka.actor.default-dispatcher-7] ERROR com.vivint.ceph.TaskActor - Unexpected error for configuration stream
akka.stream.AbruptTerminationException: Processor actor [Actor[akka://ceph-on-mesos/user/task-actor-backoff/task-actor/StreamSupervisor-1/flow-0-0-unknown-operation#692057597]] terminated abruptly
18:27:35.037 [ceph-on-mesos-akka.actor.default-dispatcher-5] INFO  com.vivint.ceph.TaskActor - pulling initial state for TaskActor
18:27:35.037 [ceph-on-mesos-akka.actor.default-dispatcher-5] DEBUG com.vivint.ceph.TaskActor - acquiring lock : pulling state
18:27:35.040 [ceph-on-mesos-akka.actor.default-dispatcher-7] ERROR akka.actor.OneForOneStrategy - Kill
akka.actor.ActorKilledException: Kill
18:27:35.041 [ceph-on-mesos-akka.actor.default-dispatcher-2] ERROR com.vivint.ceph.TaskActor - Unexpected error for configuration stream
akka.stream.AbruptTerminationException: Processor actor [Actor[akka://ceph-on-mesos/user/task-actor-backoff/task-actor/StreamSupervisor-4/flow-3-0-unknown-operation#-245605240]] terminated abruptly
18:27:35.045 [ceph-on-mesos-akka.actor.default-dispatcher-9] INFO  akka.actor.LocalActorRef - Message [akka.actor.Kill$] from Actor[akka://ceph-on-mesos/deadLetters] to Actor[akka://ceph-on-mesos/user/task-actor-backoff/task-actor#-661139218] was not delivered. [1] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
18:27:36.195 [ceph-on-mesos-akka.actor.default-dispatcher-10] INFO  com.vivint.ceph.TaskActor - pulling initial state for TaskActor
18:27:36.196 [ceph-on-mesos-akka.actor.default-dispatcher-10] DEBUG com.vivint.ceph.TaskActor - acquiring lock : pulling state```

**Comment by nicgrayson** [comment]
After a few restarts this cleared up. 🤷‍♂️
