### ISSUE TITLE
Unresolved Dependencies

### ISSUE THREAD

**Issue by jharshman** [vivint-smarthome/ceph-on-mesos#15]
When building, I am running into the following issue.

Scala Version = 2.12.3
SBT Version = 1.0.0
Java Version 1.8

``` bash
➜  ceph-on-mesos git:(master) ✗ sbt
[info] Loading settings from plugins.sbt ...
[info] Loading project definition from /ceph-on-mesos/project
[info] Updating {file:/ceph-on-mesos/project/}ceph-on-mesos-build...
[warn]  module not found: io.spray#sbt-revolver;0.8.0
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/io.spray/sbt-revolver/scala_2.12/sbt_1.0//0.8.0/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/io.spray/sbt-revolver/scala_2.12/sbt_1.0//0.8.0/ivys/ivy.xml
[warn] ==== local: tried
[warn]   /root/.ivy2/local/io.spray/sbt-revolver/scala_2.12/sbt_1.0//0.8.0/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/io/spray/sbt-revolver_2.12_1.0/0.8.0/sbt-revolver-0.8.0.pom
[warn] ==== local-preloaded-ivy: tried
[warn]   /root/.sbt/preloaded/io.spray/sbt-revolver/0.8.0/ivys/ivy.xml
[warn] ==== local-preloaded: tried
[warn]   file:////root/.sbt/preloaded/io/spray/sbt-revolver_2.12_1.0/0.8.0/sbt-revolver-0.8.0.pom
[warn]  module not found: com.typesafe.sbt#sbt-native-packager;1.1.4
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbt/sbt-native-packager/scala_2.12/sbt_1.0//1.1.4/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-native-packager/scala_2.12/sbt_1.0//1.1.4/ivys/ivy.xml
[warn] ==== local: tried
[warn]   /root/.ivy2/local/com.typesafe.sbt/sbt-native-packager/scala_2.12/sbt_1.0//1.1.4/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/typesafe/sbt/sbt-native-packager_2.12_1.0/1.1.4/sbt-native-packager-1.1.4.pom
[warn] ==== local-preloaded-ivy: tried
[warn]   /root/.sbt/preloaded/com.typesafe.sbt/sbt-native-packager/1.1.4/ivys/ivy.xml
[warn] ==== local-preloaded: tried
[warn]   file:////root/.sbt/preloaded/com/typesafe/sbt/sbt-native-packager_2.12_1.0/1.1.4/sbt-native-packager-1.1.4.pom
[warn]  module not found: org.scala-js#sbt-scalajs;0.6.13
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/org.scala-js/sbt-scalajs/scala_2.12/sbt_1.0//0.6.13/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.scala-js/sbt-scalajs/scala_2.12/sbt_1.0//0.6.13/ivys/ivy.xml
[warn] ==== local: tried
[warn]   /root/.ivy2/local/org.scala-js/sbt-scalajs/scala_2.12/sbt_1.0//0.6.13/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/org/scala-js/sbt-scalajs_2.12_1.0/0.6.13/sbt-scalajs-0.6.13.pom
[warn] ==== local-preloaded-ivy: tried
[warn]   /root/.sbt/preloaded/org.scala-js/sbt-scalajs/0.6.13/ivys/ivy.xml
[warn] ==== local-preloaded: tried
[warn]   file:////root/.sbt/preloaded/org/scala-js/sbt-scalajs_2.12_1.0/0.6.13/sbt-scalajs-0.6.13.pom
[info] downloading https://repo1.maven.org/maven2/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1-tests.jar ...
[info]  [SUCCESSFUL ] org.apache.logging.log4j#log4j-core;2.8.1!log4j-core.jar(test-jar) (419ms)
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: io.spray#sbt-revolver;0.8.0: not found
[warn]  :: com.typesafe.sbt#sbt-native-packager;1.1.4: not found
[warn]  :: org.scala-js#sbt-scalajs;0.6.13: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.                                                  [4/3152]
[warn]          io.spray:sbt-revolver:0.8.0 (scalaVersion=2.12, sbtVersion=1.0)
[warn]          com.typesafe.sbt:sbt-native-packager:1.1.4 (scalaVersion=2.12, sbtVersion=1.0)
[warn]          org.scala-js:sbt-scalajs:0.6.13 (scalaVersion=2.12, sbtVersion=1.0)
[warn] 
[warn]  Note: Unresolved dependencies path:
[warn]          io.spray:sbt-revolver:0.8.0 (scalaVersion=2.12, sbtVersion=1.0) (/ceph-on-mesos/project/plugins.sbt#L1-2)
[warn]            +- default:ceph-on-mesos-build:0.1-SNAPSHOT (scalaVersion=2.12, sbtVersion=1.0)
[warn]          com.typesafe.sbt:sbt-native-packager:1.1.4 (scalaVersion=2.12, sbtVersion=1.0) (/ceph-on-mesos/project/plugins.sbt#L3-4)
[warn]            +- default:ceph-on-mesos-build:0.1-SNAPSHOT (scalaVersion=2.12, sbtVersion=1.0)
[warn]          org.scala-js:sbt-scalajs:0.6.13 (scalaVersion=2.12, sbtVersion=1.0) (/ceph-on-mesos/project/plugins.sbt#L5-6)
[warn]            +- default:ceph-on-mesos-build:0.1-SNAPSHOT (scalaVersion=2.12, sbtVersion=1.0)
[error] sbt.librarymanagement.ResolveException: unresolved dependency: io.spray#sbt-revolver;0.8.0: not found
[error] unresolved dependency: com.typesafe.sbt#sbt-native-packager;1.1.4: not found
[error] unresolved dependency: org.scala-js#sbt-scalajs;0.6.13: not found
[error]         at sbt.internal.librarymanagement.IvyActions$.resolveAndRetrieve(IvyActions.scala:331)
[error]         at sbt.internal.librarymanagement.IvyActions$.$anonfun$updateEither$1(IvyActions.scala:205)
[error]         at sbt.internal.librarymanagement.IvySbt$Module.$anonfun$withModule$1(Ivy.scala:229)
[error]         at sbt.internal.librarymanagement.IvySbt.$anonfun$withIvy$1(Ivy.scala:190)
[error]         at sbt.internal.librarymanagement.IvySbt.sbt$internal$librarymanagement$IvySbt$$action$1(Ivy.scala:70)
[error]         at sbt.internal.librarymanagement.IvySbt$$anon$3.call(Ivy.scala:77)
[error]         at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
[error]         at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
[error]         at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
[error]         at xsbt.boot.Using$.withResource(Using.scala:10)
[error]         at xsbt.boot.Using$.apply(Using.scala:9)
[error]         at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
[error]         at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
[error]         at xsbt.boot.Locks$.apply0(Locks.scala:31)
[error]         at xsbt.boot.Locks$.apply(Locks.scala:28)
[error]         at sbt.internal.librarymanagement.IvySbt.withDefaultLogger(Ivy.scala:77)
[error]         at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:185)
[error]         at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:182)
[error]         at sbt.internal.librarymanagement.IvySbt$Module.withModule(Ivy.scala:228)
[error]         at sbt.internal.librarymanagement.IvyActions$.updateEither(IvyActions.scala:190)
[error]         at sbt.librarymanagement.ivy.IvyDependencyResolution.update(IvyDependencyResolution.scala:20)
[error]         at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:56)
[error]         at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:38)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:91)
[error]         at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:64)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$19(LibraryManagement.scala:104)
[error]         at scala.util.control.Exception$Catch.apply(Exception.scala:224)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:104)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:87)
[error]         at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:141)
[error]         at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:118)
[error]         at sbt.Classpaths$.$anonfun$updateTask$5(Defaults.scala:2313)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:42)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:64)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:257)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
[error]         at sbt.Execute.work(Execute.scala:266)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:257)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:167)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:32)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? [error] (*:update) sbt.librarymanagement.ResolveException: unresolved dependency: io.spray#sbt-revolver;0.8.0: not found
[error] unresolved dependency: com.typesafe.sbt#sbt-native-packager;1.1.4: not found
[error] unresolved dependency: org.scala-js#sbt-scalajs;0.6.13: not found
```

**Comment by jharshman** [comment]
Also FYI bintray links don't function anymore.
`curl -L -O https://dl.bintray.com/vivint-smarthome/ceph-on-mesos/ceph-on-mesos-0.2.11.tgz`
returns 403

**Comment by jharshman** [comment]
Seems to be failing to pull in dependencies because those versions aren't hosted at the URLs it is trying to resolve them from.

Does Not Exist:
``` bash
https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/io.spray/sbt-revolver/scala_2.12/sbt_1.0//0.8.0/ivys/ivy.xml
```
Does Exist:
``` bash
https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/io.spray/sbt-revolver/scala_2.12/sbt_1.0//0.9.0/ivys/ivy.xml
```

After updating the offending packages in `plugins.sbt` so they could be finally downloaded,
`sbt-revolver` updated to 0.9.0
`sbt-native-packager` updated to 1.2.2
`sbt-scalajs` updated to 0.6.19

I am now running into the following error when building,
``` bash
[warn] Found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[warn]  * com.google.guava:guava:19.0 is selected over {18.0, 10.0.1, 15.0}
[warn]      +- org.scala-js:closure-compiler-java-6:v20160517     (depends on 19.0)
[warn]      +- org.eclipse.sisu:org.eclipse.sisu.plexus:0.0.0.M5  (depends on 18.0)
[warn]      +- com.fasterxml.jackson.datatype:jackson-datatype-guava:2.6.0 (depends on 18.0)
[warn]      +- com.spotify:docker-client:3.5.13                   (depends on 18.0)
[warn]  * org.codehaus.plexus:plexus-utils:3.0.17 is selected over {2.1, 1.5.5}
[warn]      +- org.apache.maven:maven-settings:3.2.2              (depends on 3.0.17)
[warn]      +- org.apache.maven:maven-repository-metadata:3.2.2   (depends on 3.0.17)
[warn]      +- org.apache.maven:maven-aether-provider:3.2.2       (depends on 3.0.17)
[warn]      +- org.apache.maven:maven-model:3.2.2                 (depends on 3.0.17)
[warn]      +- org.apache.maven:maven-core:3.2.2                  (depends on 3.0.17)
[warn]      +- org.apache.maven:maven-artifact:3.2.2              (depends on 3.0.17)
[warn]      +- org.apache.maven:maven-settings-builder:3.2.2      (depends on 3.0.17)
[warn]      +- org.apache.maven:maven-model-builder:3.2.2         (depends on 3.0.17)
[warn]      +- org.sonatype.plexus:plexus-sec-dispatcher:1.3      (depends on 1.5.5)
[warn]      +- org.eclipse.sisu:org.eclipse.sisu.plexus:0.0.0.M5  (depends on 2.1)
[warn] Run 'evicted' to see detailed eviction warnings
```
